# Generated by Django 4.1.5 on 2023-10-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='unique',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
