# Generated by Django 4.1.5 on 2023-10-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_cart_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='unique',
            field=models.CharField(max_length=100),
        ),
    ]
