# Generated by Django 4.1.5 on 2023-10-03 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0004_alter_cart_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='unique',
        ),
    ]
